id: P9E509599
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG12287
  instance_id: http://purl.bdrc.io/resource/IE1KG8928
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - ཟབ་ཆོས་ཞི་ཁྲོ་དགོངས་པ་རང་གྲོལ།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P5245
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    bf02c1323e3243acae83f8ed90ca6035:
      title: པོད ༡་ཟབ་ཆོས་ཞི་ཁྲོ་དགོངས་པ་རང་གྲོལ།
      volume_number: 1
      base_file: UT1KG8928_I1KG9003_0000.txt
      reference: http://purl.bdrc.io/resource/VL04266EFA02947D2F
      image_group: I1KG9003
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W1KG8928
  - http://purl.bdrc.io/resource/MW1KG8928
  ocr_software: Namsel
created_at: '2021-12-22T11:01:09.283486'
last_modified_at: '2021-12-22T11:01:09.283493'
statistics:
  total_words: 96742
  total_non_words: 13090
quality:
  non_words_ratio: 0.14
